module.exports = {
    global: require('./global'),
    main: require('./main'),
    auth_first: require('./auth_first'),
    auth_opinion: require('./auth_opinion'),
    auth_autorization: require('./auth_autorization'),
    auth_help: require('./auth_help'),
    dict_main: require('./dict_main'),
    dict_tren: require('./dict_tren'),
    dict_tren_checking: require('./dict_tren_checking'),
    dict_tren_checking_confirm: require('./dict_tren_checking_confirm'),
    dict_aam: require('./dict_aam'),
    dict_addNew: require('./dict_addNew'),
    dict_addNew_getting: require('./dict_addNew_getting'),
    dict_selfSound: require('./dict_selfSound'),
    dict_regular_notification: require('./dict_regular_notification'),
    dict_ntfSet: require('./dict_ntfSet'),
    dict_ntfSet_setAttr: require('./dict_ntfSet_setAttr'),
    practice_lessons: require('./practice_lessons'),
    practice_getting_task: require('./practice_getting_task'),
    dialog: require('./dialog')
}